# Generated by Django 3.1.2 on 2020-11-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_playlist_created_by'),
        ('user', '0005_auto_20201117_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='playlists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.playlist'),
        ),
    ]
