# Generated by Django 3.1.2 on 2020-11-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='playlists',
        ),
    ]
