# Generated by Django 3.1.2 on 2020-11-06 04:48

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', audiofield.fields.AudioField(blank='True', help_text='Allowed_type - .mp3, .wav, .ogg', upload_to='audio/')),
                ('mood', models.CharField(choices=[('CHILL', 'CHILL'), ('SAD', 'SAD'), ('HAPPY', 'HAPPY'), ('ANGRY', 'ANGRY'), ('MOTIVATIONAL', 'MOTIVATIONAL'), ('DEVOTIONAL', 'DEVOTIONAL')], default='RANDOM', max_length=50)),
                ('timeline', models.CharField(choices=[("2020's", "2020's"), ("2010's", "2010's"), ("2000's", "2000's"), ("1990's", "1990's"), ("1980's", "1980's"), ("1970's", "1970's")], default='LATEST', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
            ],
        ),
    ]
