# Generated by Django 3.1.2 on 2020-11-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_created_by'),
        ('songs', '0003_auto_20201106_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='playlist.Playlist'),
        ),
    ]
