# Generated by Django 3.1.2 on 2020-11-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created_by',
        ),
    ]
